version: "3.9"
services:
    backend:
        image: api
        container_name: api
        build:
            context: ./api
        ports:
            - "9000:80"
    frontend:
        image: front
        container_name: front
        build:
            context: ./front
        ports:
            - "4200:80"
        depends_on:
            - backend
